services:
  littlelink-server:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    networks:
      - traefik_default
    environment:
      - META_TITLE=kevinjodea.com
      - META_DESCRIPTION=
      - META_AUTHOR=Kevin James O'Dea
      - META_KEYWORDS=
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=kevinjodea.com
      - OG_TITLE=kevinjodea.com
      - OG_DESCRIPTION=
      - OG_URL=https://kevinjodea.com
      - OG_IMAGE=
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      # - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=Dark
      - FAVICON_URL=https://em-content.zobj.net/source/serenityos/392/penguin_1f427.png
      - AVATAR_URL=https://avatars.githubusercontent.com/u/94148295
      - AVATAR_2X_URL=
      - AVATAR_ALT=Kevin James O'Dea Profile Picture
      - NAME=Kevin James O'Dea
      - BIO=Linux Systems Administrator @ualibraries
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=UAL,LINKED_IN,GITHUB,INSTAGRAM,BANDCAMP,YOUTUBE
      # you can render an unlimited amount of custom buttons by adding
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - CUSTOM_BUTTON_TEXT=UArizona Libraries
      - CUSTOM_BUTTON_URL=https://lib.arizona.edu/people/kevin-odea
      - CUSTOM_BUTTON_COLOR=#AB0520
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff
      - CUSTOM_BUTTON_ALT_TEXT=UArizona Libraries Profile
      - CUSTOM_BUTTON_NAME=UAL
      - CUSTOM_BUTTON_ICON=fa-solid fa-book-open
      - GITHUB=https://github.com/kev1njodea
      - INSTAGRAM=https://instagram.com/kevinjodea
      - LINKED_IN=https://www.linkedin.com/in/kevinjodea/
      - BANDCAMP=https://bandcamp.com/kevinjodea
      - YOUTUBE=https://www.youtube.com/@KevinJODea
      - FOOTER=Go Vegan 🌱
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.http.routers.littlelink.rule=Host(`kevinjodea.com`)"
      - "traefik.http.routers.littlelink.entrypoints=web-secure"
      - "traefik.http.routers.littlelink.tls=true"
      - "traefik.http.services.littlelink.loadbalancer.server.port=3000"
      - "traefik.http.services.littlelink.loadbalancer.server.scheme=http"

networks:
  traefik_default:
    external: true
